In [1]:
import pandas as pd
df = pd.read_csv('C:/Users/CHK/Desktop/Final_Project/data/car_price_prediction/model9/processed_0415.csv')

# 1. 데이터 전처리

##### 1) 무의미한 컬럼 drop

In [2]:
df.drop(['Unnamed: 0', 'SEQ'], axis=1, inplace=True)

##### 2) 컬럼 순서 정렬

In [3]:
new_order = ['LMNAME', 'MNAME'] + [col for col in df.columns if col not in ['LMNAME', 'MNAME']]
df = df[new_order]
df.head()

,LMNAME,MNAME,MYEAR,VNUM,PRICE,MILEAGE,COLOR,TRANS,F_TYPE,DISP,VTYPE,CU_HIS,MVD_HIS,AVD_HIS,TL_HIS,FD_HIS,VT_HIS,US_HIS,TLHIS
0,기아 봉고3 윙바디 탑차,기아 봉고,2018년08월(19년형),92너0923,173.0,80800.0,흰색,자동,디젤,2497.0,트럭,NaN,1.0,5.0,0.0,0.0,0.0,4.0,NaN
1,기아 더 K9 3.3 AWD,기아 K9,2022년01월(22년형),183너2180,522.0,52600.0,검정색,자동,가솔린,3342.0,대형,NaN,0.0,0.0,0.0,0.0,0.0,1.0,NaN
2,현대 더 뉴 제네시스 쿠페 2.0 터보 S,현대 제네시스쿠페,2012년05월(12년형),30고8622,95.0,156291.0,흰색,자동,가솔린,1998.0,스포츠카,NaN,1.0,1.0,0.0,0.0,0.0,7.0,NaN
3,현대 제네시스 쿠페 2.0 터보 R,현대 제네시스쿠페,2010년02월(10년형),20도3968,63.0,174361.0,검정색,자동,가솔린,1998.0,스포츠카,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KG모빌리티 티볼리 1.6 디젤 2WD TX,KG모빌리티 티볼리,2016년03월(16년형),65구0993,57.9,122000.0,흰색,자동,디젤,1597.0,SUV,NaN,5.0,3.0,0.0,0.0,0.0,2.0,NaN

##### 3) NaN값 0으로 처리

In [4]:
df = df.fillna(0)
df.head()

,LMNAME,MNAME,MYEAR,VNUM,PRICE,MILEAGE,COLOR,TRANS,F_TYPE,DISP,VTYPE,CU_HIS,MVD_HIS,AVD_HIS,TL_HIS,FD_HIS,VT_HIS,US_HIS,TLHIS
0,기아 봉고3 윙바디 탑차,기아 봉고,2018년08월(19년형),92너0923,173.0,80800.0,흰색,자동,디젤,2497.0,트럭,0.0,1.0,5.0,0.0,0.0,0.0,4.0,0.0
1,기아 더 K9 3.3 AWD,기아 K9,2022년01월(22년형),183너2180,522.0,52600.0,검정색,자동,가솔린,3342.0,대형,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,현대 더 뉴 제네시스 쿠페 2.0 터보 S,현대 제네시스쿠페,2012년05월(12년형),30고8622,95.0,156291.0,흰색,자동,가솔린,1998.0,스포츠카,0.0,1.0,1.0,0.0,0.0,0.0,7.0,0.0
3,현대 제네시스 쿠페 2.0 터보 R,현대 제네시스쿠페,2010년02월(10년형),20도3968,63.0,174361.0,검정색,자동,가솔린,1998.0,스포츠카,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,KG모빌리티 티볼리 1.6 디젤 2WD TX,KG모빌리티 티볼리,2016년03월(16년형),65구0993,57.9,122000.0,흰색,자동,디젤,1597.0,SUV,0.0,5.0,3.0,0.0,0.0,0.0,2.0,0.0

##### 4) 모델명 빈도수 30 미만 행 삭제

In [5]:
mname_counts = df['MNAME'].value_counts()

# 빈도수가 30 미만인 행의 인덱스 추출
rows_to_delete = mname_counts[mname_counts < 30].index

# 빈도수가 30 미만인 행 삭제
df = df[~df['MNAME'].isin(rows_to_delete)]

# 변경된 DataFrame을 사용하거나 필요에 따라 새로운 파일로 저장
# 예를 들어, 변경된 DataFrame을 'new_data.csv' 파일로 저장하는 경우
df.to_csv('new_data.csv', index=False)

##### 5) 추가 전처리(불용 컬럼 삭제, 값 통일, get_dummies 등)

In [24]:
new_df = pd.read_csv('C:/Users/CHK/Desktop/Final_Project/model/car_price_prediction/new_data.csv')
new_df.loc[new_df['COLOR'] == '인기색상', 'COLOR'] = '흰색'
new_df.loc[new_df['MNAME'] == '현대 펠리세이드', 'MNAME'] = '현대 팰리세이드'
new_df['MYEAR'] = new_df['MYEAR'].str.extract(r'(\d{4})')
new_df['MYEAR'] = pd.to_numeric(new_df['MYEAR'], errors='coerce')
new_df.head()

,LMNAME,MNAME,MYEAR,VNUM,PRICE,MILEAGE,COLOR,TRANS,F_TYPE,DISP,VTYPE,CU_HIS,MVD_HIS,AVD_HIS,TL_HIS,FD_HIS,VT_HIS,US_HIS,TLHIS
0,기아 봉고3 윙바디 탑차,기아 봉고,2018,92너0923,173.0,80800.0,흰색,자동,디젤,2497.0,트럭,0.0,1.0,5.0,0.0,0.0,0.0,4.0,0.0
1,기아 더 K9 3.3 AWD,기아 K9,2022,183너2180,522.0,52600.0,검정색,자동,가솔린,3342.0,대형,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,현대 더 뉴 제네시스 쿠페 2.0 터보 S,현대 제네시스쿠페,2012,30고8622,95.0,156291.0,흰색,자동,가솔린,1998.0,스포츠카,0.0,1.0,1.0,0.0,0.0,0.0,7.0,0.0
3,현대 제네시스 쿠페 2.0 터보 R,현대 제네시스쿠페,2010,20도3968,63.0,174361.0,검정색,자동,가솔린,1998.0,스포츠카,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,KG모빌리티 티볼리 1.6 디젤 2WD TX,KG모빌리티 티볼리,2016,65구0993,57.9,122000.0,흰색,자동,디젤,1597.0,SUV,0.0,5.0,3.0,0.0,0.0,0.0,2.0,0.0

In [25]:
new_df.drop(['VTYPE', 'VNUM', 'LMNAME'], axis=1, inplace=True)
new_df = pd.get_dummies(new_df, columns=['COLOR', 'TRANS', 'F_TYPE'])
new_df['MYEAR'] = 2024 - new_df['MYEAR'] + 1
new_df.head()

,MNAME,MYEAR,PRICE,MILEAGE,DISP,CU_HIS,MVD_HIS,AVD_HIS,TL_HIS,FD_HIS,...,F_TYPE_가솔린+LPG,F_TYPE_가솔린/LPG겸용,F_TYPE_기타,F_TYPE_디젤,F_TYPE_전기,F_TYPE_하이브리드,F_TYPE_하이브리드(LPG),F_TYPE_하이브리드(가솔린),F_TYPE_하이브리드(가솔린/전기),F_TYPE_하이브리드(디젤)
0,기아 봉고,7,173.0,80800.0,2497.0,0.0,1.0,5.0,0.0,0.0,...,False,False,False,True,False,False,False,False,False,False
1,기아 K9,3,522.0,52600.0,3342.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
2,현대 제네시스쿠페,13,95.0,156291.0,1998.0,0.0,1.0,1.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
3,현대 제네시스쿠페,15,63.0,174361.0,1998.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
4,KG모빌리티 티볼리,9,57.9,122000.0,1597.0,0.0,5.0,3.0,0.0,0.0,...,False,False,False,True,False,False,False,False,False,False

In [46]:
new_df.shape

(27801, 307)

In [48]:
new_df.dtypes

MNAME                    object
MYEAR                     int64
PRICE                    object
MILEAGE                 float64
DISP                    float64
                         ...
F_TYPE_하이브리드               bool
F_TYPE_하이브리드(LPG)          bool
F_TYPE_하이브리드(가솔린)          bool
F_TYPE_하이브리드(가솔린/전기)       bool
F_TYPE_하이브리드(디젤)           bool
Length: 307, dtype: object

In [51]:
new_df = new_df[new_df['PRICE'] != '리스승계']
new_df['PRICE'] = pd.to_numeric(new_df['PRICE'], errors='coerce')
new_df = new_df[new_df['PRICE'] < 300000]

In [52]:
new_df.shape

(27800, 307)

In [53]:
new_df.to_csv('pre-processed_data2.csv')

# 2. 모델링

In [27]:
import pandas as pd
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import mean_squared_error

##### 1) 자동차 모델별 XGB Regressor 학습

In [54]:
# MNAME의 고유값을 가져옵니다.
mname_values = new_df['MNAME'].unique()

# 앙상블을 위한 모델 리스트 생성
models = []

# 각 MNAME에 대한 모델 훈련
for mname in mname_values:
    # 특정 MNAME에 해당하는 데이터만 추출
    mname_data = new_df[new_df['MNAME'] == mname]
    
    # 특성과 타겟 데이터 분리
    X = mname_data.drop(columns=['PRICE', 'MNAME'])
    y = mname_data['PRICE']
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # XGBoost Regressor 모델 훈련
    model = XGBRegressor()
    model.fit(X_train, y_train)
    
    # 모델을 모델 리스트에 추가
    models.append(('model_' + mname, model))

In [55]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

# 각 모델의 테스트 데이터에 대한 MSE를 저장할 리스트 생성
mse_values = {}
mae_values = {}

# 각 MNAME에 대한 모델에 대해 반복하여 MSE 계산
for mname in mname_values:
    # 특정 MNAME에 해당하는 데이터만 추출
    mname_data = new_df[new_df['MNAME'] == mname]
    
    # 특성과 타겟 데이터 분리
    X_test = mname_data.drop(columns=['PRICE', 'MNAME'])
    y_test = mname_data['PRICE']
    
    # 모델을 가져옴
    model_name = 'model_' + mname
    model = dict(models)[model_name]
    
    # 모델을 사용하여 테스트 데이터에 대한 예측값 계산
    y_pred = model.predict(X_test)
    
    # MSE 계산 및 결과 출력
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    print(f'Model {mname}의 MSE: {mse}')
    print(f'Model {mname}의 MAE: {mae}')
    
    # MSE 값을 리스트에 추가
    mse_values[mname] = mse
    mae_values[mname] = mae

Model 기아 봉고의 MSE: 27830.75422439232
Model 기아 봉고의 MAE: 71.56685278246479
Model 기아 K9의 MSE: 67027.46921899203
Model 기아 K9의 MAE: 87.40704208822811
Model 현대 제네시스쿠페의 MSE: 13353.132940775171
Model 현대 제네시스쿠페의 MAE: 32.21015021745549
Model KG모빌리티 티볼리의 MSE: 10445.705941490485
Model KG모빌리티 티볼리의 MAE: 34.176050841290014
Model 기아 카니발의 MSE: 40497.741279878355
Model 기아 카니발의 MAE: 114.35646286293836
Model 현대 쏘나타의 MSE: 12938.187785336657
Model 현대 쏘나타의 MAE: 47.28625663006244
Model 현대 아반떼의 MSE: 14926.812323903427
Model 현대 아반떼의 MAE: 43.15755774022225
Model 기아 K7의 MSE: 14350.357916717323
Model 기아 K7의 MAE: 46.930926936560304
Model 르노코리아 QM3의 MSE: 1924.8432842997784
Model 르노코리아 QM3의 MAE: 16.883781895493016
Model 기아 쏘렌토의 MSE: 17178.977587227604
Model 기아 쏘렌토의 MAE: 54.30176740115202
Model 제네시스 G80의 MSE: 55197.44041167417
Model 제네시스 G80의 MAE: 62.43733963828555
Model 제네시스 G90의 MSE: 143822.18261200152
Model 제네시스 G90의 MAE: 84.4020393499514
Model 현대 그랜저의 MSE: 124571.8296952285
Model 현대 그랜저의 MAE: 86.21957199377842
Model 현대 포터의 MSE: 5253885.211720746
Model 현대 포터의 MAE: 155.2916800427165
Model 현대 코나의 MSE: 35162.18108379832
Model 현대 코나의 MAE: 63.00944245312665
Model 기아 스포티지의 MSE: 6382.624249671707
Model 기아 스포티지의 MAE: 31.418956407904627
Model 기아 K8의 MSE: 20521.178981490975
Model 기아 K8의 MAE: 61.5753200677725
Model 기아 모하비의 MSE: 26130.16212716593
Model 기아 모하비의 MAE: 50.980021747789884
Model 제네시스 GV80의 MSE: 46306.14597177896
Model 제네시스 GV80의 MAE: 69.10172031169036
Model 현대 싼타페의 MSE: 30066.2355307325
Model 현대 싼타페의 MAE: 67.6437473357418
Model 현대 팰리세이드의 MSE: 45859.347238135255
Model 현대 팰리세이드의 MAE: 72.51008451676228
Model 현대 아이오닉의 MSE: 22040.74583237882
Model 현대 아이오닉의 MAE: 52.49566845261907
Model 현대 제네시스의 MSE: 3700.4748400488756
Model 현대 제네시스의 MAE: 21.18499299869981
Model 기아 스팅어의 MSE: 49725.690596241395
Model 기아 스팅어의 MAE: 75.80050143680057
Model 현대 맥스크루즈의 MSE: 29240.60057066382
Model 현대 맥스크루즈의 MAE: 51.16277761307974
Model 제네시스 EQ900의 MSE: 176941.8178097153
Model 제네시스 EQ900의 MAE: 126.16476197676225
Model KG모빌리티 렉스턴의 MSE: 25853.09415650911
Model KG모빌리티 렉스턴의 MAE: 52.77344199180603
Model 제네시스 G70의 MSE: 4662324.801615823
Model 제네시스 G70의 MAE: 510.4472417195993
Model 기아 K5의 MSE: 16730.461507828477
Model 기아 K5의 MAE: 44.385136104135384
Model 르노코리아 SM6의 MSE: 3848.096865790394
Model 르노코리아 SM6의 MAE: 22.62526358710395
Model 기아 셀토스의 MSE: 9951.110368722144
Model 기아 셀토스의 MAE: 36.81012559678819
Model 기아 K3의 MSE: 14689.876480320096
Model 기아 K3의 MAE: 40.169728112654255
Model 기아 쏘울의 MSE: 5230.718316595516
Model 기아 쏘울의 MAE: 22.191867574055987
Model 현대 투싼의 MSE: 13029.470796068583
Model 현대 투싼의 MAE: 37.60450067217824
Model 현대 캐스퍼의 MSE: 20436.759364760048
Model 현대 캐스퍼의 MAE: 50.528642645547556
Model 현대 에쿠스의 MSE: 6379.795947973385
Model 현대 에쿠스의 MAE: 25.26693381919517
Model 기아 모닝의 MSE: 3041.876989454828
Model 기아 모닝의 MAE: 22.575414641443597
Model 현대 벨로스터의 MSE: 38375.70243046935
Model 현대 벨로스터의 MAE: 52.12714226764181
Model KG모빌리티 코란도의 MSE: 5645.191811469742
Model KG모빌리티 코란도의 MAE: 25.781188007023022
Model 현대 스타리아의 MSE: 331191.82529397565
Model 현대 스타리아의 MAE: 186.2444028009342
Model 현대 스타렉스의 MSE: 27245.117169164136
Model 현대 스타렉스의 MAE: 57.31734691260843
Model 현대 마이티의 MSE: 183548.81035993985
Model 현대 마이티의 MAE: 140.79650261288597
Model 르노코리아 SM7의 MSE: 23254.565547671442
Model 르노코리아 SM7의 MAE: 58.12879238617726
Model 르노코리아 SM5의 MSE: 1265.2952708988926
Model 르노코리아 SM5의 MAE: 10.943086642310734
Model 현대 i40의 MSE: 8314.418572985549
Model 현대 i40의 MAE: 32.852213679133236
Model 르노코리아 QM6의 MSE: 15182.150684922244
Model 르노코리아 QM6의 MAE: 41.12193168477809
Model 기아 니로의 MSE: 25172.647486939855
Model 기아 니로의 MAE: 49.504062463602885
Model 기아 레이의 MSE: 19170.35735453011
Model 기아 레이의 MAE: 53.00987059523017
Model 현대 베뉴의 MSE: 60878.31739845584
Model 현대 베뉴의 MAE: 63.41259037364613
Model 현대 엑센트의 MSE: 5935.574377427387
Model 현대 엑센트의 MAE: 20.69534158706665
Model 현대 i30의 MSE: 9541.669313657652
Model 현대 i30의 MAE: 37.71461238031802
Model 르노코리아 SM3의 MSE: 3151.825996524951
Model 르노코리아 SM3의 MAE: 17.100675201416017
Model 기아 카렌스의 MSE: 4166.011874373989
Model 기아 카렌스의 MAE: 20.720664349724267
Model 한국GM 스파크의 MSE: 3519.8682988484998
Model 한국GM 스파크의 MAE: 40.04326163123428
Model 한국GM 트랙스의 MSE: 14183.735862283515
Model 한국GM 트랙스의 MAE: 34.1990201116322
Model 한국GM 크루즈의 MSE: 4487.8814387817665
Model 한국GM 크루즈의 MAE: 30.044017462082852
Model 한국GM 캡티바의 MSE: 2490.4611576175307
Model 한국GM 캡티바의 MAE: 18.944292606451572
Model 기아 프라이드의 MSE: 1214.366587297627
Model 기아 프라이드의 MAE: 12.343181818181819
Model 한국GM 마티즈의 MSE: 1157.1118135039562
Model 한국GM 마티즈의 MAE: 13.70116214094491
Model 기아 스토닉의 MSE: 2673.257479991983
Model 기아 스토닉의 MAE: 18.822621065027572
Model 한국GM 말리부의 MSE: 10257.384095665042
Model 한국GM 말리부의 MAE: 45.792243375906494
Model 한국GM 올란도의 MSE: 3054.9438290029243
Model 한국GM 올란도의 MAE: 23.855450229790375
Model 한국GM 라보의 MSE: 2087.434706821974
Model 한국GM 라보의 MAE: 15.131333356584822
Model 한국GM 라세티의 MSE: 889.0625462324596
Model 한국GM 라세티의 MAE: 11.264755194527762
Model 한국GM 다마스의 MSE: 133986.97662586017
Model 한국GM 다마스의 MAE: 43.533380090837646
Model 한국GM 임팔라의 MSE: 4282.705832074599
Model 한국GM 임팔라의 MAE: 22.6003590459409
Model 한국GM 아베오의 MSE: 4460.1923338089055
Model 한국GM 아베오의 MAE: 24.095113805822425
Model 한국GM 알페온의 MSE: 3720.1411559124394
Model 한국GM 알페온의 MAE: 20.54785178364187
Model 한국GM 카마로의 MSE: 62017.62134443456
Model 한국GM 카마로의 MAE: 76.84451675415039
Model 한국GM 트래버스의 MSE: 37379.406675879225
Model 한국GM 트래버스의 MAE: 59.10599009195963
Model 한국GM 볼트의 MSE: 14983.645133069333
Model 한국GM 볼트의 MAE: 49.94664091222427
Model 한국GM 콜로라도의 MSE: 92435.27505263245
Model 한국GM 콜로라도의 MAE: 89.20900698061342
Model 한국GM 윈스톰의 MSE: 18793.082260856245
Model 한국GM 윈스톰의 MAE: 35.1470951178135
Model BMW X4의 MSE: 616183.6477845734
Model BMW X4의 MAE: 229.17765682894034
Model BMW 5시리즈의 MSE: 286290.42698418174
Model BMW 5시리즈의 MAE: 231.27302888119695
Model BMW 3시리즈의 MSE: 282637.7362235781
Model BMW 3시리즈의 MAE: 184.53646537235804
Model BMW X3의 MSE: 121393.55590378193
Model BMW X3의 MAE: 119.52502144086228
Model BMW 그란투리스모의 MSE: 244527.85346339457
Model BMW 그란투리스모의 MAE: 118.80249459402901
Model BMW X1의 MSE: 257316.02915051184
Model BMW X1의 MAE: 126.63108507093493
Model BMW 4시리즈의 MSE: 86744.93347230674
Model BMW 4시리즈의 MAE: 101.51929361012084
Model BMW 7시리즈의 MSE: 568494.0854176985
Model BMW 7시리즈의 MAE: 213.81129764615832
Model BMW X6의 MSE: 1464493.2474314976
Model BMW X6의 MAE: 308.47838310092686
Model BMW 1시리즈의 MSE: 163794.7657346234
Model BMW 1시리즈의 MAE: 103.74325952080774
Model BMW X5의 MSE: 954616.2147461966
Model BMW X5의 MAE: 219.10052941711655
Model BMW M시리즈의 MSE: 650537.3845660994
Model BMW M시리즈의 MAE: 270.9981281744467
Model BMW Z4의 MSE: 680647.9287824278
Model BMW Z4의 MAE: 263.05785748969623
Model BMW X7의 MSE: 3784145.4460438984
Model BMW X7의 MAE: 555.7998763825286
Model BMW 6시리즈의 MSE: 626779.2635237259
Model BMW 6시리즈의 MAE: 227.76135500971577
Model BMW 2시리즈의 MSE: 1283941.2957182082
Model BMW 2시리즈의 MAE: 254.00978096463342
Model 벤츠 S클래스의 MSE: 1373486.479213034
Model 벤츠 S클래스의 MAE: 431.1986097337851
Model 벤츠 CLS클래스의 MSE: 347631.89107362187
Model 벤츠 CLS클래스의 MAE: 172.67463598833973
Model 벤츠 GLA의 MSE: 4815786.236095537
Model 벤츠 GLA의 MAE: 503.30568840740517
Model 벤츠 C클래스의 MSE: 365252.9820501067
Model 벤츠 C클래스의 MAE: 195.96746641560122
Model 벤츠 E클래스의 MSE: 611161.7592681162
Model 벤츠 E클래스의 MAE: 314.04514879287916
Model 벤츠 GLE의 MSE: 833471.0841722857
Model 벤츠 GLE의 MAE: 256.59064019061475
Model 벤츠 GLK클래스의 MSE: 28330.04151013866
Model 벤츠 GLK클래스의 MAE: 64.9267463684082
Model 벤츠 A클래스의 MSE: 490385.0398018684
Model 벤츠 A클래스의 MAE: 170.9512157516212
Model 벤츠 CLA클래스의 MSE: 122225.08875241503
Model 벤츠 CLA클래스의 MAE: 112.06785287355122
Model 벤츠 GLC의 MSE: 628960.8355631294
Model 벤츠 GLC의 MAE: 197.39081955642152
Model 벤츠 M클래스의 MSE: 19099.126827715354
Model 벤츠 M클래스의 MAE: 48.64027786254883
Model 벤츠 GLB의 MSE: 46701.28497754746
Model 벤츠 GLB의 MAE: 77.88933847464767
Model 벤츠 AMG의 MSE: 2928725.9327324
Model 벤츠 AMG의 MAE: 554.7914754180681
Model 벤츠 G클래스의 MSE: 12125151.588600542
Model 벤츠 G클래스의 MAE: 925.6828202797122
Model 벤츠 B클래스의 MSE: 284120.19420615974
Model 벤츠 B클래스의 MAE: 95.81192779541016
Model 벤츠 GLS의 MSE: 2713579.520387169
Model 벤츠 GLS의 MAE: 586.7751514499867

In [56]:
mae_values

{'기아 봉고': 71.56685278246479,
 '기아 K9': 87.40704208822811,
 '현대 제네시스쿠페': 32.21015021745549,
 'KG모빌리티 티볼리': 34.176050841290014,
 '기아 카니발': 114.35646286293836,
 '현대 쏘나타': 47.28625663006244,
 '현대 아반떼': 43.15755774022225,
 '기아 K7': 46.930926936560304,
 '르노코리아 QM3': 16.883781895493016,
 '기아 쏘렌토': 54.30176740115202,
 '제네시스 G80': 62.43733963828555,
 '제네시스 G90': 84.4020393499514,
 '현대 그랜저': 86.21957199377842,
 '현대 포터': 155.2916800427165,
 '현대 코나': 63.00944245312665,
 '기아 스포티지': 31.418956407904627,
 '기아 K8': 61.5753200677725,
 '기아 모하비': 50.980021747789884,
 '제네시스 GV80': 69.10172031169036,
 '현대 싼타페': 67.6437473357418,
 '현대 팰리세이드': 72.51008451676228,
 '현대 아이오닉': 52.49566845261907,
 '현대 제네시스': 21.18499299869981,
 '기아 스팅어': 75.80050143680057,
 '현대 맥스크루즈': 51.16277761307974,
 '제네시스 EQ900': 126.16476197676225,
 'KG모빌리티 렉스턴': 52.77344199180603,
 '제네시스 G70': 510.4472417195993,
 '기아 K5': 44.385136104135384,
 '르노코리아 SM6': 22.62526358710395,
 '기아 셀토스': 36.81012559678819,
 '기아 K3': 40.169728112654255,
 '기아 쏘울': 22.191867574055987,
 '현대 투싼': 37.60450067217824,
 '현대 캐스퍼': 50.528642645547556,
 '현대 에쿠스': 25.26693381919517,
 '기아 모닝': 22.575414641443597,
 '현대 벨로스터': 52.12714226764181,
 'KG모빌리티 코란도': 25.781188007023022,
 '현대 스타리아': 186.2444028009342,
 '현대 스타렉스': 57.31734691260843,
 '현대 마이티': 140.79650261288597,
 '르노코리아 SM7': 58.12879238617726,
 '르노코리아 SM5': 10.943086642310734,
 '현대 i40': 32.852213679133236,
 '르노코리아 QM6': 41.12193168477809,
 '기아 니로': 49.504062463602885,
 '기아 레이': 53.00987059523017,
 '현대 베뉴': 63.41259037364613,
 '현대 엑센트': 20.69534158706665,
 '현대 i30': 37.71461238031802,
 '르노코리아 SM3': 17.100675201416017,
 '기아 카렌스': 20.720664349724267,
 '한국GM 스파크': 40.04326163123428,
 '한국GM 트랙스': 34.1990201116322,
 '한국GM 크루즈': 30.044017462082852,
 '한국GM 캡티바': 18.944292606451572,
 '기아 프라이드': 12.343181818181819,
 '한국GM 마티즈': 13.70116214094491,
 '기아 스토닉': 18.822621065027572,
 '한국GM 말리부': 45.792243375906494,
 '한국GM 올란도': 23.855450229790375,
 '한국GM 라보': 15.131333356584822,
 '한국GM 라세티': 11.264755194527762,
 '한국GM 다마스': 43.533380090837646,
 '한국GM 임팔라': 22.6003590459409,
 '한국GM 아베오': 24.095113805822425,
 '한국GM 알페온': 20.54785178364187,
 '한국GM 카마로': 76.84451675415039,
 '한국GM 트래버스': 59.10599009195963,
 '한국GM 볼트': 49.94664091222427,
 '한국GM 콜로라도': 89.20900698061342,
 '한국GM 윈스톰': 35.1470951178135,
 'BMW X4': 229.17765682894034,
 'BMW 5시리즈': 231.27302888119695,
 'BMW 3시리즈': 184.53646537235804,
 'BMW X3': 119.52502144086228,
 'BMW 그란투리스모': 118.80249459402901,
 'BMW X1': 126.63108507093493,
 'BMW 4시리즈': 101.51929361012084,
 'BMW 7시리즈': 213.81129764615832,
 'BMW X6': 308.47838310092686,
 'BMW 1시리즈': 103.74325952080774,
 'BMW X5': 219.10052941711655,
 'BMW M시리즈': 270.9981281744467,
 'BMW Z4': 263.05785748969623,
 'BMW X7': 555.7998763825286,
 'BMW 6시리즈': 227.76135500971577,
 'BMW 2시리즈': 254.00978096463342,
 '벤츠 S클래스': 431.1986097337851,
 '벤츠 CLS클래스': 172.67463598833973,
 '벤츠 GLA': 503.30568840740517,
 '벤츠 C클래스': 195.96746641560122,
 '벤츠 E클래스': 314.04514879287916,
 '벤츠 GLE': 256.59064019061475,
 '벤츠 GLK클래스': 64.9267463684082,
 '벤츠 A클래스': 170.9512157516212,
 '벤츠 CLA클래스': 112.06785287355122,
 '벤츠 GLC': 197.39081955642152,
 '벤츠 M클래스': 48.64027786254883,
 '벤츠 GLB': 77.88933847464767,
 '벤츠 AMG': 554.7914754180681,
 '벤츠 G클래스': 925.6828202797122,
 '벤츠 B클래스': 95.81192779541016,
 '벤츠 GLS': 586.7751514499867}

In [57]:
import numpy as np

In [58]:
values = list(mae_values.values())

# numpy의 percentile 함수를 사용하여 분위수 계산
q1 = np.percentile(values, 25)
q2 = np.percentile(values, 50)  # 중앙값과 동일하므로 50번째 백분위수
q3 = np.percentile(values, 75)
q4 = np.percentile(values, 100) # 최대값과 동일하므로 100번째 백분위수

print("1분위수 (25번째 백분위수):", q1)
print("2분위수 (중앙값, 50번째 백분위수):", q2)
print("3분위수 (75번째 백분위수):", q3)
print("4분위수 (100번째 백분위수, 최댓값):", q4)

1분위수 (25번째 백분위수): 34.1990201116322
2분위수 (중앙값, 50번째 백분위수): 58.12879238617726
3분위수 (75번째 백분위수): 126.63108507093493
4분위수 (100번째 백분위수, 최댓값): 925.6828202797122

In [65]:
import csv

# 딕셔너리 생성 예시

# CSV 파일에 딕셔너리의 키와 값을 쓰기
with open('mae.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    
    # 헤더를 쓰기
    writer.writerow(['Key', 'Value'])
    
    # 각 키와 값을 쓰기
    for key, value in mae_values.items():
        writer.writerow([key, value])

print("CSV 파일이 성공적으로 저장되었습니다.")

CSV 파일이 성공적으로 저장되었습니다.

In [60]:
# 'model 현대 포터'를 찾아서 해당 모델을 사용하여 예측값 계산
for model_name, model in models:
    if model_name == 'model_현대 팰리세이드':
        # 현대 포터 데이터만 추출
        hyundai_porter_data = new_df[new_df['MNAME'] == '현대 팰리세이드']
        
        # 특성과 타겟 데이터 분리
        X_hyundai_porter = hyundai_porter_data.drop(columns=['PRICE', 'MNAME'])
        y_hyundai_porter_actual = hyundai_porter_data['PRICE']
        
        # 모델을 사용하여 예측값 계산
        y_hyundai_porter_pred = model.predict(X_hyundai_porter)
        
        # 실제값과 예측값 출력
        for actual, pred in zip(y_hyundai_porter_actual, y_hyundai_porter_pred):
            print("실제값:", actual, "| 예측값:", pred)

실제값: 445.0 | 예측값: 448.9506
실제값: 246.0 | 예측값: 253.33975
실제값: 249.9 | 예측값: 252.03247
실제값: 229.0 | 예측값: 267.6111
실제값: 448.0 | 예측값: 447.49622
실제값: 332.0 | 예측값: 591.97894
실제값: 259.9 | 예측값: 260.508
실제값: 278.0 | 예측값: 276.14633
실제값: 398.5 | 예측값: 395.11743
실제값: 315.0 | 예측값: 767.84784
실제값: 20.0 | 예측값: 15.50503
실제값: 278.0 | 예측값: 278.39505
실제값: 20.0 | 예측값: 28.432087
실제값: 285.0 | 예측값: 286.34436
실제값: 395.0 | 예측값: 396.6502
실제값: 340.0 | 예측값: 344.37717
실제값: 330.0 | 예측값: 260.9259
실제값: 385.0 | 예측값: 380.22333
실제값: 250.0 | 예측값: 252.82617
실제값: 389.0 | 예측값: 385.4635
실제값: 445.0 | 예측값: 446.63678
실제값: 365.0 | 예측값: 365.63293
실제값: 2600.0 | 예측값: 2598.63
실제값: 4420.0 | 예측값: 4415.3306
실제값: 3499.0 | 예측값: 3508.43
실제값: 3190.0 | 예측값: 3127.78
실제값: 3430.0 | 예측값: 3437.0308
실제값: 2650.0 | 예측값: 2652.8594
실제값: 3190.0 | 예측값: 3190.2576
실제값: 3420.0 | 예측값: 3420.6133
실제값: 3890.0 | 예측값: 3910.2427
실제값: 2980.0 | 예측값: 2974.3828
실제값: 2950.0 | 예측값: 2936.0308
실제값: 5050.0 | 예측값: 3894.2188
실제값: 3340.0 | 예측값: 3327.1384
실제값: 5750.0 | 예측값: 5749.0493
실제값: 2750.0 | 예측값: 2744.554
실제값: 2430.0 | 예측값: 2453.506
실제값: 4550.0 | 예측값: 4526.1885
실제값: 3430.0 | 예측값: 3436.735
실제값: 3550.0 | 예측값: 3567.3948
실제값: 2599.0 | 예측값: 2600.1143
실제값: 2790.0 | 예측값: 3074.185
실제값: 4950.0 | 예측값: 4939.517
실제값: 2499.0 | 예측값: 2511.528
실제값: 3150.0 | 예측값: 3083.508
실제값: 2799.0 | 예측값: 2859.8857
실제값: 3090.0 | 예측값: 3070.9421
실제값: 3590.0 | 예측값: 3560.8335
실제값: 3120.0 | 예측값: 3130.0088
실제값: 3350.0 | 예측값: 3352.6836
실제값: 2990.0 | 예측값: 2965.5916
실제값: 2750.0 | 예측값: 2735.556
실제값: 2539.0 | 예측값: 2531.448
실제값: 3500.0 | 예측값: 3505.2375
실제값: 3790.0 | 예측값: 4433.5815
실제값: 3550.0 | 예측값: 3546.358
실제값: 2980.0 | 예측값: 2755.2856
실제값: 3890.0 | 예측값: 3891.5415
실제값: 3899.0 | 예측값: 3905.022
실제값: 2820.0 | 예측값: 2828.8037
실제값: 3480.0 | 예측값: 3475.1387
실제값: 3390.0 | 예측값: 3399.2764
실제값: 4699.0 | 예측값: 3712.7295
실제값: 3800.0 | 예측값: 3795.4316
실제값: 2250.0 | 예측값: 2247.8555
실제값: 3600.0 | 예측값: 2687.0073
실제값: 2870.0 | 예측값: 2870.6458
실제값: 2750.0 | 예측값: 2777.1523
실제값: 3799.0 | 예측값: 3801.1604
실제값: 2770.0 | 예측값: 2762.8035
실제값: 3050.0 | 예측값: 3047.921
실제값: 2769.0 | 예측값: 3029.1714
실제값: 3200.0 | 예측값: 2684.948
실제값: 3900.0 | 예측값: 3900.7683
실제값: 2780.0 | 예측값: 2778.558
실제값: 3099.0 | 예측값: 3489.2095
실제값: 2980.0 | 예측값: 3214.283
실제값: 3280.0 | 예측값: 3402.0447
실제값: 2750.0 | 예측값: 2745.5073
실제값: 2530.0 | 예측값: 2532.3252
실제값: 4380.0 | 예측값: 4369.154
실제값: 3150.0 | 예측값: 3548.9207
실제값: 2840.0 | 예측값: 2837.7498
실제값: 4900.0 | 예측값: 3751.5408
실제값: 2790.0 | 예측값: 2805.1934
실제값: 4700.0 | 예측값: 4675.637
실제값: 2630.0 | 예측값: 2627.0735
실제값: 3150.0 | 예측값: 3157.8003
실제값: 2650.0 | 예측값: 2650.6428
실제값: 2890.0 | 예측값: 2888.1118
실제값: 2990.0 | 예측값: 2987.0964
실제값: 2870.0 | 예측값: 2864.1213
실제값: 2650.0 | 예측값: 2658.6335
실제값: 950.0 | 예측값: 905.77527
실제값: 950.0 | 예측값: 949.64795
실제값: 1700.0 | 예측값: 1700.1403
실제값: 250.0 | 예측값: 257.50345
실제값: 3080.0 | 예측값: 3077.9202
실제값: 3190.0 | 예측값: 3175.317
실제값: 2990.0 | 예측값: 3008.2432
실제값: 1350.0 | 예측값: 975.76733
실제값: 1740.0 | 예측값: 1741.8657
실제값: 1450.0 | 예측값: 1450.3434
실제값: 4390.0 | 예측값: 4389.0757
실제값: 1000.0 | 예측값: 1005.98285
실제값: 590.0 | 예측값: 594.1633
실제값: 450.0 | 예측값: 449.5322
실제값: 1370.0 | 예측값: 1160.6138
실제값: 1980.0 | 예측값: 1854.655
실제값: 2350.0 | 예측값: 2444.2095
실제값: 2490.0 | 예측값: 2341.7883
실제값: 3300.0 | 예측값: 3292.238
실제값: 2295.0 | 예측값: 2777.002
실제값: 3100.0 | 예측값: 2835.8567
실제값: 2550.0 | 예측값: 2545.972
실제값: 1290.0 | 예측값: 2809.9497
실제값: 349.0 | 예측값: 359.04608
실제값: 2690.0 | 예측값: 3017.4272
실제값: 3750.0 | 예측값: 3750.5298
실제값: 3590.0 | 예측값: 3583.7996
실제값: 1480.0 | 예측값: 1508.7836
실제값: 1030.0 | 예측값: 1017.6262
실제값: 2699.0 | 예측값: 2702.4592
실제값: 210.0 | 예측값: 215.7225
실제값: 1880.0 | 예측값: 1882.1227
실제값: 2490.0 | 예측값: 1726.8619
실제값: 2350.0 | 예측값: 2355.9163
실제값: 2990.0 | 예측값: 2981.733
실제값: 1370.0 | 예측값: 1377.5305
실제값: 3280.0 | 예측값: 3293.1409
실제값: 1140.0 | 예측값: 1150.2856
실제값: 4380.0 | 예측값: 3394.4119
실제값: 4950.0 | 예측값: 4947.607
실제값: 870.0 | 예측값: 873.34906
실제값: 1190.0 | 예측값: 1187.5533
실제값: 530.0 | 예측값: 538.43115
실제값: 3280.0 | 예측값: 3284.6104
실제값: 2350.0 | 예측값: 2352.449
실제값: 1910.0 | 예측값: 1913.5724
실제값: 2370.0 | 예측값: 2367.3516
실제값: 1230.0 | 예측값: 1220.3438
실제값: 4250.0 | 예측값: 4218.8687
실제값: 890.0 | 예측값: 897.598
실제값: 1620.0 | 예측값: 2566.2576
실제값: 1330.0 | 예측값: 1328.7555
실제값: 2750.0 | 예측값: 2151.251
실제값: 240.0 | 예측값: 239.37718
실제값: 1050.0 | 예측값: 1049.9172
실제값: 2750.0 | 예측값: 2750.4312
실제값: 1400.0 | 예측값: 1407.7925
실제값: 1349.0 | 예측값: 1355.3983
실제값: 1950.0 | 예측값: 1950.4331
실제값: 3570.0 | 예측값: 3646.2397
실제값: 600.0 | 예측값: 604.10864
실제값: 830.0 | 예측값: 829.6055
실제값: 690.0 | 예측값: 690.05206
실제값: 2550.0 | 예측값: 2577.0225
실제값: 350.0 | 예측값: 356.90027
실제값: 2850.0 | 예측값: 2843.621
실제값: 2599.0 | 예측값: 2584.9692
실제값: 2020.0 | 예측값: 2024.4075
실제값: 2320.0 | 예측값: 2305.9468
실제값: 1099.0 | 예측값: 1100.7681
실제값: 3760.0 | 예측값: 3743.3857
실제값: 2780.0 | 예측값: 2891.087
실제값: 1450.0 | 예측값: 1439.5212
실제값: 2850.0 | 예측값: 2854.367
실제값: 1830.0 | 예측값: 1816.9451
실제값: 490.0 | 예측값: 493.751
실제값: 2350.0 | 예측값: 2372.3525
실제값: 3440.0 | 예측값: 3457.4258
실제값: 1080.0 | 예측값: 1081.1317
실제값: 4999.0 | 예측값: 4999.718
실제값: 1290.0 | 예측값: 1284.686
실제값: 1080.0 | 예측값: 1350.1084
실제값: 890.0 | 예측값: 880.8733
실제값: 3350.0 | 예측값: 3352.4734
실제값: 1230.0 | 예측값: 1231.5537
실제값: 3399.0 | 예측값: 3400.9988
실제값: 2899.0 | 예측값: 3384.3574
실제값: 1210.0 | 예측값: 1207.7549
실제값: 880.0 | 예측값: 741.4495
실제값: 4650.0 | 예측값: 4651.4565
실제값: 1030.0 | 예측값: 1020.49976
실제값: 470.0 | 예측값: 504.36035
실제값: 3980.0 | 예측값: 3955.7615
실제값: 620.0 | 예측값: 622.1056
실제값: 2650.0 | 예측값: 2654.529
실제값: 399.0 | 예측값: 393.95535
실제값: 3350.0 | 예측값: 3352.8057
실제값: 2379.0 | 예측값: 2381.8271
실제값: 3680.0 | 예측값: 3691.075
실제값: 1099.0 | 예측값: 1099.3691
실제값: 1250.0 | 예측값: 1247.0762
실제값: 2750.0 | 예측값: 3445.0085
실제값: 1590.0 | 예측값: 1372.4451
실제값: 630.0 | 예측값: 627.16406
실제값: 1659.0 | 예측값: 1656.3358
실제값: 2700.0 | 예측값: 2791.0725
실제값: 1730.0 | 예측값: 1728.658
실제값: 2549.0 | 예측값: 2550.2346
실제값: 1920.0 | 예측값: 1944.4379
실제값: 690.0 | 예측값: 988.8219
실제값: 990.0 | 예측값: 979.2016
실제값: 2749.0 | 예측값: 2747.847
실제값: 3270.0 | 예측값: 3261.257
실제값: 2890.0 | 예측값: 2883.0708
실제값: 3190.0 | 예측값: 3189.2688
실제값: 2400.0 | 예측값: 3028.621
실제값: 2800.0 | 예측값: 2825.9077
실제값: 2850.0 | 예측값: 3227.6128
실제값: 1830.0 | 예측값: 1841.3588
실제값: 2800.0 | 예측값: 2811.2278
실제값: 1619.0 | 예측값: 1617.0154
실제값: 2580.0 | 예측값: 2568.2656
실제값: 790.0 | 예측값: 811.6119
실제값: 2190.0 | 예측값: 2204.5935
실제값: 1849.0 | 예측값: 1851.904
실제값: 2490.0 | 예측값: 2493.1018
실제값: 2050.0 | 예측값: 2058.2236
실제값: 750.0 | 예측값: 742.8404
실제값: 2690.0 | 예측값: 2533.3684
실제값: 3870.0 | 예측값: 3826.8533
실제값: 2490.0 | 예측값: 2487.8655
실제값: 1280.0 | 예측값: 1281.1027
실제값: 3299.0 | 예측값: 3284.118
실제값: 930.0 | 예측값: 930.75116
실제값: 2150.0 | 예측값: 2157.9202
실제값: 3000.0 | 예측값: 3023.8306
실제값: 2449.0 | 예측값: 2440.0442
실제값: 3790.0 | 예측값: 3784.1753
실제값: 1480.0 | 예측값: 1484.2113
실제값: 3469.0 | 예측값: 3487.4807
실제값: 1499.0 | 예측값: 1502.3237
실제값: 2410.0 | 예측값: 2409.8945
실제값: 3450.0 | 예측값: 3441.6301
실제값: 3850.0 | 예측값: 4176.8804
실제값: 2100.0 | 예측값: 2099.2903
실제값: 2380.0 | 예측값: 2382.1243
실제값: 1050.0 | 예측값: 1046.5627
실제값: 3790.0 | 예측값: 3809.2134
실제값: 699.0 | 예측값: 706.1666
실제값: 2850.0 | 예측값: 2834.3643
실제값: 1950.0 | 예측값: 1963.7788
실제값: 650.0 | 예측값: 650.73987
실제값: 650.0 | 예측값: 682.6287
실제값: 470.0 | 예측값: 476.41638
실제값: 2580.0 | 예측값: 2580.556
실제값: 389.0 | 예측값: 394.23447
실제값: 2000.0 | 예측값: 1998.4517
실제값: 1470.0 | 예측값: 1467.4207
실제값: 3650.0 | 예측값: 3615.366
실제값: 700.0 | 예측값: 698.2938
실제값: 1830.0 | 예측값: 1826.4274
실제값: 800.0 | 예측값: 807.34186
실제값: 1890.0 | 예측값: 1884.8322
실제값: 470.0 | 예측값: 470.69556
실제값: 499.0 | 예측값: 500.66492
실제값: 1450.0 | 예측값: 1445.4465
실제값: 1750.0 | 예측값: 1332.4855
실제값: 1590.0 | 예측값: 1585.4176
실제값: 2690.0 | 예측값: 2682.4487
실제값: 3950.0 | 예측값: 3940.6633
실제값: 1329.0 | 예측값: 1347.5488
실제값: 740.0 | 예측값: 752.53467
실제값: 1880.0 | 예측값: 1875.1803
실제값: 590.0 | 예측값: 581.376
실제값: 599.0 | 예측값: 594.16473
실제값: 1530.0 | 예측값: 1526.8544
실제값: 1490.0 | 예측값: 1484.2865
실제값: 770.0 | 예측값: 768.58997
실제값: 1799.0 | 예측값: 1802.0795
실제값: 1180.0 | 예측값: 1183.0323
실제값: 450.0 | 예측값: 458.82867
실제값: 2279.0 | 예측값: 2282.3677
실제값: 1650.0 | 예측값: 1646.4573
실제값: 480.0 | 예측값: 477.83817
실제값: 1190.0 | 예측값: 1189.667
실제값: 340.0 | 예측값: 337.7991
실제값: 1680.0 | 예측값: 1678.1938
실제값: 5350.0 | 예측값: 5334.8145
실제값: 1930.0 | 예측값: 1935.5114
실제값: 920.0 | 예측값: 912.4944
실제값: 3150.0 | 예측값: 3152.9414
실제값: 1179.0 | 예측값: 1145.0105
실제값: 1050.0 | 예측값: 1044.3693
실제값: 2180.0 | 예측값: 2174.0916
실제값: 960.0 | 예측값: 960.7888
실제값: 2380.0 | 예측값: 2397.5127
실제값: 1699.0 | 예측값: 1703.1782
실제값: 790.0 | 예측값: 792.6858
실제값: 1730.0 | 예측값: 1572.0461
실제값: 1120.0 | 예측값: 1116.6079
실제값: 570.0 | 예측값: 568.3091
실제값: 2290.0 | 예측값: 2290.9822
실제값: 550.0 | 예측값: 556.51874
실제값: 2200.0 | 예측값: 2213.917
실제값: 1550.0 | 예측값: 1548.7277
실제값: 2149.0 | 예측값: 2147.7085
실제값: 1150.0 | 예측값: 1398.804
실제값: 1340.0 | 예측값: 1352.4058
실제값: 900.0 | 예측값: 899.0605
실제값: 4130.0 | 예측값: 4129.934
실제값: 2970.0 | 예측값: 2975.745
실제값: 499.0 | 예측값: 597.8022
실제값: 1400.0 | 예측값: 1397.5668
실제값: 1419.0 | 예측값: 1419.1213
실제값: 2149.0 | 예측값: 2146.259
실제값: 850.0 | 예측값: 832.24146
실제값: 2600.0 | 예측값: 2605.507
실제값: 1800.0 | 예측값: 1804.4617
실제값: 599.0 | 예측값: 590.7176
실제값: 2270.0 | 예측값: 2245.5767
실제값: 2470.0 | 예측값: 2470.4744
실제값: 3450.0 | 예측값: 3470.901
실제값: 2770.0 | 예측값: 2467.4622
실제값: 999.0 | 예측값: 1159.0951
실제값: 670.0 | 예측값: 807.903
실제값: 3350.0 | 예측값: 3344.2048
실제값: 820.0 | 예측값: 907.67596
실제값: 1170.0 | 예측값: 1167.2771
실제값: 1650.0 | 예측값: 1658.6416
실제값: 4940.0 | 예측값: 4933.0225
실제값: 1480.0 | 예측값: 1478.2882
실제값: 3110.0 | 예측값: 3109.8079
실제값: 5840.0 | 예측값: 5833.053
실제값: 590.0 | 예측값: 585.5597
실제값: 2450.0 | 예측값: 3093.5327
실제값: 460.0 | 예측값: 458.17896
실제값: 5380.0 | 예측값: 4278.0474
실제값: 2599.0 | 예측값: 2582.9316
실제값: 1010.0 | 예측값: 1009.3995
실제값: 2300.0 | 예측값: 2188.7058
실제값: 1510.0 | 예측값: 1508.4233
실제값: 1850.0 | 예측값: 1851.1201
실제값: 1050.0 | 예측값: 1050.0386
실제값: 4400.0 | 예측값: 4393.875

In [40]:
new_df[new_df['MNAME']=='현대 팰리세이드'].to_csv('팰리세이드.csv')

In [64]:
# '현대 팰리세이드' 모델 찾기
target_model_name = '기아 카니발'
target_model = None

for name, model in models:
    if name == 'model_' + target_model_name:
        target_model = model
        break

if target_model:
    # '현대 팰리세이드' 모델의 가중치 확인
    feature_importance_df = pd.DataFrame(target_model.feature_importances_, index=X.columns, columns=['Importance'])
    print(feature_importance_df)
else:
    print("해당 모델을 찾을 수 없습니다.")

feature_importance_df.to_csv('기아 카니발 가중치.csv')

                      Importance
MYEAR                   0.101680
MILEAGE                 0.027090
DISP                    0.005400
CU_HIS                  0.014189
MVD_HIS                 0.000580
...                          ...
F_TYPE_하이브리드            0.000000
F_TYPE_하이브리드(LPG)       0.000000
F_TYPE_하이브리드(가솔린)       0.010328
F_TYPE_하이브리드(가솔린/전기)    0.000000
F_TYPE_하이브리드(디젤)        0.000000

[305 rows x 1 columns]

In [62]:
feature_importance_df.to_csv('팰리세이드 가중치.csv')